# DO NOT EDIT THIS FILE!
#
# Python module RTR generated by omniidl

import omniORB
omniORB.updateModule("RTR")

# ** 1. Stub files contributing to this module
import test_idl

# ** 2. Sub-modules

# ** 3. End
